// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.System.Data;

#nullable disable

namespace Restaurant.System.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817094506_AddDropdown")]
    partial class AddDropdown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.System.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderSession")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber");

                    b.ToTable("CustomerOrder", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Dropdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Dropdown", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MemberPoint")
                        .HasColumnType("numeric");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MenuName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MenuCategory", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItem", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MenuDays")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MenuSchedule", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MenuCode")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleCode")
                        .HasColumnType("text");

                    b.Property<string>("SectionCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("MenuCode");

                    b.HasIndex("ScheduleCode");

                    b.ToTable("MenuSection", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text");

                    b.Property<string>("StaffUsername")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalOrderAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StaffUsername");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.OrderGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("OrderGroup", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MenuItemCode")
                        .HasColumnType("text");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderItemStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderGroupId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMessage")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.StaffRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleCode")
                        .HasColumnType("text");

                    b.Property<string>("StaffUsername")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode");

                    b.HasIndex("StaffUsername");

                    b.ToTable("StaffRoles", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LogoutDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.CustomerOrder", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.Customer", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.System.Models.Entities.Order", "Order")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("OrderNumber")
                        .HasPrincipalKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Member", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.Customer", "Customer")
                        .WithOne("MemberDetails")
                        .HasForeignKey("Restaurant.System.Models.Entities.Member", "CustomerId")
                        .HasPrincipalKey("Restaurant.System.Models.Entities.Customer", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Restaurant.System.Models.Entities.Address", "AddressList", b1 =>
                        {
                            b1.Property<Guid>("AddressGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsDefaultAddress")
                                .HasColumnType("boolean");

                            b1.Property<int>("MemberId")
                                .HasColumnType("integer");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .HasColumnType("text");

                            b1.HasKey("AddressGuid");

                            b1.HasIndex("MemberId");

                            b1.ToTable("Address", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("AddressList");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuItem", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.MenuCategory", "Category")
                        .WithMany("MenuItemList")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuSection", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.MenuCategory", "Category")
                        .WithMany("MenuSections")
                        .HasForeignKey("CategoryCode")
                        .HasPrincipalKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Restaurant.System.Models.Entities.Menu", "Menu")
                        .WithMany("MenuSections")
                        .HasForeignKey("MenuCode")
                        .HasPrincipalKey("MenuCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Restaurant.System.Models.Entities.MenuSchedule", "MenuSchedule")
                        .WithMany("MenuSectionList")
                        .HasForeignKey("ScheduleCode")
                        .HasPrincipalKey("ScheduleCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Menu");

                    b.Navigation("MenuSchedule");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.Staff", "Staff")
                        .WithMany("OrderHistory")
                        .HasForeignKey("StaffUsername")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Restaurant.System.Models.Entities.OrderAddress", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("AddressGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("OrderId")
                                .HasColumnType("integer");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .HasColumnType("text");

                            b1.HasKey("AddressGuid");

                            b1.HasIndex("OrderId")
                                .IsUnique();

                            b1.ToTable("OrderAddress", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.OrderGroup", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.Order", "Order")
                        .WithMany("OrderGroups")
                        .HasForeignKey("OrderNumber")
                        .HasPrincipalKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId");

                    b.HasOne("Restaurant.System.Models.Entities.OrderGroup", "OrderGroup")
                        .WithMany("OrderItemList")
                        .HasForeignKey("OrderGroupId")
                        .HasPrincipalKey("OrderGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderGroup");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Payment", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Restaurant.System.Models.Entities.Payment", "OrderNumber")
                        .HasPrincipalKey("Restaurant.System.Models.Entities.Order", "OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.StaffRoles", b =>
                {
                    b.HasOne("Restaurant.System.Models.Entities.Role", "Role")
                        .WithMany("StaffRolesList")
                        .HasForeignKey("RoleCode")
                        .HasPrincipalKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Restaurant.System.Models.Entities.Staff", "Staff")
                        .WithMany("StaffRolesList")
                        .HasForeignKey("StaffUsername")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Customer", b =>
                {
                    b.Navigation("CustomerOrders");

                    b.Navigation("MemberDetails");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Menu", b =>
                {
                    b.Navigation("MenuSections");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuCategory", b =>
                {
                    b.Navigation("MenuItemList");

                    b.Navigation("MenuSections");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.MenuSchedule", b =>
                {
                    b.Navigation("MenuSectionList");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Order", b =>
                {
                    b.Navigation("CustomerOrders");

                    b.Navigation("OrderGroups");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.OrderGroup", b =>
                {
                    b.Navigation("OrderItemList");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Role", b =>
                {
                    b.Navigation("StaffRolesList");
                });

            modelBuilder.Entity("Restaurant.System.Models.Entities.Staff", b =>
                {
                    b.Navigation("OrderHistory");

                    b.Navigation("StaffRolesList");
                });
#pragma warning restore 612, 618
        }
    }
}
